name: Build and Deploy
on:
  # pull_request:
  push:
    branches:
      - main
    # types: [closed]

jobs:
  build-and-deploy: # job id
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1

      - name: Install and Build ğŸ”§
        run: |
          yarn install
          yarn build

      - name: Copy vercel.sh
        run: |
          cp ./vercel.sh ./dist/vercel.sh

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: for-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
